name: "Commit messages adheres to guidelines at https://goo.gl/p2fr5Q"

on: [pull_request]

env:
  NODE_VERSION: lts/*

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Compute number of commits in the PR
        id: nb-of-commits
        run: echo "::set-output name=nb::$((${{ github.event.pull_request.commits }} + 1))"
      - uses: actions/checkout@v2
        with:
          fetch-depth: ${{ steps.nb-of-commits.outputs.nb }}
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Validate commit messages
        run: |
          echo "::add-matcher::.github/workflows/commit-lint-problem-matcher.json"
          git log --oneline -${{ github.event.pull_request.commits }} HEAD^ | awk '{ if ($2 != "fixup!" && $2 != "squash!") { print $1 } }' | xargs npx -q core-validate-commit --no-validate-metadata --tap
